// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-verticals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var verticals = [
  { key: "beauty", brand: "Ghidul Beauty", domain: "ghidbeauty.ro" },
  { key: "veterinari", brand: "Ghidul Veterinarilor", domain: "ghidveterinari.ro" },
  { key: "funerare", brand: "Ghidul Funerare", domain: "ghidfunerare.ro" },
  { key: "tractari", brand: "Ghidul Tractari", domain: "ghidtractari.ro" },
  { key: "gradinite", brand: "Ghidul Gradinite", domain: "ghidgradinite.ro" },
  { key: "usi", brand: "Ghidul Usi", domain: "ghidusi.ro" },
  { key: "curatenie", brand: "Ghidul Curatenie", domain: "ghidcuratenie.ro" }
];
var list_verticals_default = defineTool({
  name: "list_verticals",
  title: "List directory verticals",
  description: "List all business directory verticals available on the platform (beauty, veterinari, funerare, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(verticals, null, 2) }],
    structuredContent: { verticals }
  })
});

// src/lib/mcp/tools/search-listings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var listings = [
  { id: "1", name: "Glamour Studio", category: "Saloane", city: "Bucure\u0219ti", county: "Bucure\u0219ti", rating: 4.9, reviewCount: 128, plan: "profesional" },
  { id: "2", name: "Zen Spa & Relax", category: "Spa & Wellness", city: "Cluj-Napoca", county: "Cluj", rating: 4.8, reviewCount: 95, plan: "profesional" },
  { id: "3", name: "NailArt Pro", category: "Unghii", city: "Timi\u0219oara", county: "Timi\u0219", rating: 4.7, reviewCount: 67, plan: "intro" },
  { id: "4", name: "Beauty Queens", category: "Cosmetic\u0103", city: "Ia\u0219i", county: "Ia\u0219i", rating: 4.6, reviewCount: 54, plan: "intro" },
  { id: "5", name: "Ink Master Studio", category: "Tatuaje", city: "Bra\u0219ov", county: "Bra\u0219ov", rating: 4.9, reviewCount: 112, plan: "profesional" },
  { id: "6", name: "Perfect Brows", category: "PMU", city: "Constan\u021Ba", county: "Constan\u021Ba", rating: 4.5, reviewCount: 43, plan: "gratuit" },
  { id: "7", name: "SunKiss Tanning", category: "Bronzare", city: "Oradea", county: "Bihor", rating: 4.3, reviewCount: 31, plan: "gratuit" },
  { id: "8", name: "The Barber House", category: "Barbershop", city: "Sibiu", county: "Sibiu", rating: 4.8, reviewCount: 89, plan: "intro" }
];
var search_listings_default = defineTool2({
  name: "search_listings",
  title: "Search business listings",
  description: "Search directory listings by free-text query, category, or city. All filters are optional; when none are provided, returns the top listings.",
  inputSchema: {
    query: z.string().trim().min(1).optional().describe("Free-text query matched against listing name and category."),
    category: z.string().trim().min(1).optional().describe("Category name to filter by (e.g. Saloane, Spa & Wellness)."),
    city: z.string().trim().min(1).optional().describe("City name to filter by."),
    limit: z.number().int().min(1).max(50).optional().describe("Max number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category, city, limit }) => {
    const q = query?.toLowerCase();
    const cat = category?.toLowerCase();
    const cty = city?.toLowerCase();
    const results = listings.filter((l) => !q || l.name.toLowerCase().includes(q) || l.category.toLowerCase().includes(q)).filter((l) => !cat || l.category.toLowerCase() === cat).filter((l) => !cty || l.city.toLowerCase() === cty).slice(0, limit ?? 10);
    return {
      content: [{ type: "text", text: JSON.stringify(results, null, 2) }],
      structuredContent: { results, count: results.length }
    };
  }
});

// src/lib/mcp/tools/get-listing.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var listings2 = {
  "1": { id: "1", name: "Glamour Studio", category: "Saloane", city: "Bucure\u0219ti", county: "Bucure\u0219ti", rating: 4.9, reviewCount: 128, plan: "profesional", description: "Salon premium de \xEEnfrumuse\u021Bare cu servicii complete de coafur\u0103, cosmetic\u0103 \u0219i manichiur\u0103." },
  "2": { id: "2", name: "Zen Spa & Relax", category: "Spa & Wellness", city: "Cluj-Napoca", county: "Cluj", rating: 4.8, reviewCount: 95, plan: "profesional", description: "Centru de wellness \u0219i spa cu tratamente faciale, masaj \u0219i relaxare." },
  "3": { id: "3", name: "NailArt Pro", category: "Unghii", city: "Timi\u0219oara", county: "Timi\u0219", rating: 4.7, reviewCount: 67, plan: "intro", description: "Studio profesional de nail art cu tehnici moderne \u0219i produse premium." },
  "4": { id: "4", name: "Beauty Queens", category: "Cosmetic\u0103", city: "Ia\u0219i", county: "Ia\u0219i", rating: 4.6, reviewCount: 54, plan: "intro", description: "Salon de cosmetic\u0103 cu tratamente faciale avansate." },
  "5": { id: "5", name: "Ink Master Studio", category: "Tatuaje", city: "Bra\u0219ov", county: "Bra\u0219ov", rating: 4.9, reviewCount: 112, plan: "profesional", description: "Studio de tatuaje cu arti\u0219ti premia\u021Bi interna\u021Bional." },
  "6": { id: "6", name: "Perfect Brows", category: "PMU", city: "Constan\u021Ba", county: "Constan\u021Ba", rating: 4.5, reviewCount: 43, plan: "gratuit", description: "Studio PMU cu tehnici microblading \u0219i powder brows." },
  "7": { id: "7", name: "SunKiss Tanning", category: "Bronzare", city: "Oradea", county: "Bihor", rating: 4.3, reviewCount: 31, plan: "gratuit", description: "Salon de bronzare cu aparate de ultim\u0103 genera\u021Bie." },
  "8": { id: "8", name: "The Barber House", category: "Barbershop", city: "Sibiu", county: "Sibiu", rating: 4.8, reviewCount: 89, plan: "intro", description: "Barbershop modern cu servicii complete de b\u0103rbierit clasic." }
};
var get_listing_default = defineTool3({
  name: "get_listing",
  title: "Get listing details",
  description: "Fetch full details for a directory listing by its id.",
  inputSchema: { id: z2.string().trim().min(1).describe("The listing id (e.g. '1').") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ id }) => {
    const listing = listings2[id];
    if (!listing) {
      return { content: [{ type: "text", text: `No listing with id '${id}'.` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(listing, null, 2) }],
      structuredContent: { listing }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "ghid-directory-mcp",
  title: "Ghid Directory MCP",
  version: "0.1.0",
  instructions: "Tools for the Ghid business directory platform (beauty, veterinari, funerare and more). Use `list_verticals` to see available directories, `search_listings` to find businesses by query/category/city, and `get_listing` to fetch full details for a specific listing id.",
  tools: [list_verticals_default, search_listings_default, get_listing_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
